webOglasnik/Controllers/KategorijaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using webOglasnik.Misc;
using webOglasnik.Models;

namespace webOglasnik.Controllers
{
    [Authorize(Roles = OvlastiKorisnik.Administrator)]
    public class KategorijaController : Controller
    {
        private BazaDbContext db = new BazaDbContext();
        
        [OverrideAuthorization]
        [AllowAnonymous]
        // GET: Kategorija
        public ActionResult Index()
        {
            return View(db.PopisKategorija.ToList());
        }

        // GET: Kategorija/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategorija kategorija = db.PopisKategorija.Find(id);
            if (kategorija == null)
            {
                return HttpNotFound();
            }
            return View(kategorija);
        }

        // GET: Kategorija/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Kategorija/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Sifra,Naziv")] Kategorija kategorija)
        {
            if (ModelState.IsValid)
            {
                db.PopisKategorija.Add(kategorija);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kategorija);
        }

        // GET: Kategorija/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategorija kategorija = db.PopisKategorija.Find(id);
            if (kategorija == null)
            {
                return HttpNotFound();
            }
            return View(kategorija);
        }

        // POST: Kategorija/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Sifra,Naziv")] Kategorija kategorija)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kategorija).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kategorija);
        }

        // GET: Kategorija/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategorija kategorija = db.PopisKategorija.Find(id);
            if (kategorija == null)
            {
                return HttpNotFound();
            }
            return View(kategorija);
        }

        // POST: Kategorija/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Kategorija kategorija = db.PopisKategorija.Find(id);
            db.PopisKategorija.Remove(kategorija);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

webOglasnik/Controllers/OglasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using webOglasnik.Models;

namespace webOglasnik.Controllers
{
    public class OglasController : Controller
    {
        public BazaDbContext db = new BazaDbContext();

        // GET: Oglas
        public ActionResult Index(string naziv, string kategorija)
        {
            var oglasi = db.PopisOglasa.ToList();

            var kategorijeList = db.PopisKategorija.OrderBy(x=>x.Naziv).ToList();
            ViewBag.Kategorije = kategorijeList;

            if (!String.IsNullOrWhiteSpace(naziv))
                oglasi = oglasi.Where(x => x.Naziv.ToUpper().Contains(naziv.ToUpper())).ToList();
             
            if (!String.IsNullOrWhiteSpace(kategorija))
                oglasi = oglasi.Where(x=>x.KategorijaSifra == kategorija).ToList();
                

            return View(oglasi);
        }
        
        // GET: Oglas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oglas oglas = db.PopisOglasa.Find(id);
            if (oglas == null)
            {
                return HttpNotFound();
            }
            return View(oglas);
        }

        [Authorize]
        // GET: Oglas/Create
        public ActionResult Create()
        {
            var kategorije = db.PopisKategorija.OrderBy(x => x.Naziv).ToList();
            kategorije.Insert(0, new Kategorija { Sifra = "", Naziv = "Nedefinirano" });
            ViewBag.Kategorije = kategorije;

            return View();
        }


        // POST: Oglas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Oglas oglas)
        {
            if (oglas.ImageFile != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(oglas.ImageFile.FileName);
                string extension = Path.GetExtension(oglas.ImageFile.FileName);

                if (extension == ".jpg" || extension == ".jpeg" || extension == ".png")
                {
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    oglas.SlikaPutanja = "~/Images/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
                    oglas.ImageFile.SaveAs(fileName);
                }
                else
                {
                    ModelState.AddModelError("SlikaPutanja", "Nepodržana ekstenzija");
                }

            }

            if (ModelState.IsValid)
            {
                db.PopisOglasa.Add(oglas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(oglas);
        }
        [Authorize]
        // GET: Oglas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oglas oglas = db.PopisOglasa.Find(id);
            if (oglas == null)
            {
                return HttpNotFound();
            }

            var kategorije = db.PopisKategorija.OrderBy(x => x.Naziv).ToList();
            kategorije.Insert(0, new Kategorija { Sifra = "", Naziv = "Nedefinirano" });
            ViewBag.Kategorije = kategorije;

            return View(oglas);
        }

        // POST: Oglas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Oglas oglas)
        {
            if (oglas.ImageFile != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(oglas.ImageFile.FileName);
                string extension = Path.GetExtension(oglas.ImageFile.FileName);

                if (extension == ".jpg" || extension == ".jpeg" || extension == ".png")
                {
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    oglas.SlikaPutanja = "~/Images/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
                    oglas.ImageFile.SaveAs(fileName);
                }
                else
                {
                    ModelState.AddModelError("SlikaPutanja", "Nepodržana ekstenzija");
                }

            }

            if (ModelState.IsValid)
            {
                db.Entry(oglas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var kategorije = db.PopisKategorija.OrderBy(x => x.Naziv).ToList();
            kategorije.Insert(0, new Kategorija { Sifra = "", Naziv = "Nedefinirano" });
            ViewBag.Kategorije = kategorije;

            return View(oglas);
        }

        // GET: Oglas/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oglas oglas = db.PopisOglasa.Find(id);
            if (oglas == null)
            {
                return HttpNotFound();
            }
            return View(oglas);
        }

        // POST: Oglas/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Oglas oglas = db.PopisOglasa.Find(id);
            db.PopisOglasa.Remove(oglas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

webOglasnik/Views/Shared/_Layout.cshtml
@using webOglasnik.Misc
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
   
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Web Oglasnik", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Oglasi", "Index", "Oglas", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Kategorije", "Index", "Kategorija", new { area = "" }, new { @class = "nav-link" })</li>

                    @if (User.Identity.IsAuthenticated && (User as LogiraniKorisnik).IsInRole(OvlastiKorisnik.Administrator))
                    {
                        <li>@Html.ActionLink("Korisnici", "Index", "Korisnici", new { area = "" }, new { @class = "nav-link" }))</li>
                    }

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink(((User as LogiraniKorisnik).PrezimeIme), "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Odjava", "Odjava", "Korisnici", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Prijava", "Prijava", "Korisnici", new { area = "" }, new { @class = "btn btn-light" })</li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Paup - Web Oglasnik </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>